//! Embedded icon and artwork assets.
//!
//! GPUI ships no icon set, so the 48 Adwaita symbolic icons the GTK build relied
//! on by name are replaced by a self-contained 16x16 stroke set generated by
//! `tools/gen_icons.py` and baked in with `include_bytes!`. That drops the GTK
//! build's habit of writing assets to a temp directory at startup, because
//! GPUI resolves them through an in-process [`AssetSource`] instead.
//!
//! Two kinds of asset live here:
//!
//! * **chrome icons** (`icons/*.svg`) are monochrome and drawn with `currentColor`,
//!   so they are rendered with [`gpui::svg`] and tinted per call site.
//! * **artwork** (`art/*.svg`) is full-colour and is rendered with [`gpui::img`],
//!   which rasterises SVG without the alpha-mask tinting that `svg()` applies.

use std::borrow::Cow;

use gpui::prelude::*;
use gpui::{AssetSource, ImageSource, Img, Result, Rgba, SharedString, Svg, px, svg};

macro_rules! asset_table {
    ($($name:literal => $path:literal,)*) => {
        /// Every embedded asset, keyed by the path GPUI will ask for.
        pub const ASSETS: &[(&str, &[u8])] = &[
            $(($name, include_bytes!($path)),)*
        ];
    };
}

asset_table! {
    // ── chrome ──────────────────────────────────────────────────────────────
    "icons/audio-x-generic.svg" => "../assets/icons/audio-x-generic.svg",
    "icons/camera-photo.svg" => "../assets/icons/camera-photo.svg",
    "icons/checkbox-checked.svg" => "../assets/icons/checkbox-checked.svg",
    "icons/dialog-error.svg" => "../assets/icons/dialog-error.svg",
    "icons/dialog-information.svg" => "../assets/icons/dialog-information.svg",
    "icons/dialog-warning.svg" => "../assets/icons/dialog-warning.svg",
    "icons/document-edit.svg" => "../assets/icons/document-edit.svg",
    "icons/document-open.svg" => "../assets/icons/document-open.svg",
    "icons/drive-harddisk.svg" => "../assets/icons/drive-harddisk.svg",
    "icons/edit-copy.svg" => "../assets/icons/edit-copy.svg",
    "icons/edit-delete.svg" => "../assets/icons/edit-delete.svg",
    "icons/edit-find.svg" => "../assets/icons/edit-find.svg",
    "icons/edit-paste.svg" => "../assets/icons/edit-paste.svg",
    "icons/edit-undo.svg" => "../assets/icons/edit-undo.svg",
    "icons/emblem-synchronizing.svg" => "../assets/icons/emblem-synchronizing.svg",
    "icons/folder.svg" => "../assets/icons/folder.svg",
    "icons/folder-documents.svg" => "../assets/icons/folder-documents.svg",
    "icons/folder-download.svg" => "../assets/icons/folder-download.svg",
    "icons/folder-music.svg" => "../assets/icons/folder-music.svg",
    "icons/folder-new.svg" => "../assets/icons/folder-new.svg",
    "icons/folder-open.svg" => "../assets/icons/folder-open.svg",
    "icons/folder-pictures.svg" => "../assets/icons/folder-pictures.svg",
    "icons/folder-send.svg" => "../assets/icons/folder-send.svg",
    "icons/folder-upload.svg" => "../assets/icons/folder-upload.svg",
    "icons/folder-videos.svg" => "../assets/icons/folder-videos.svg",
    "icons/go-next.svg" => "../assets/icons/go-next.svg",
    "icons/go-previous.svg" => "../assets/icons/go-previous.svg",
    "icons/go-up.svg" => "../assets/icons/go-up.svg",
    "icons/help-about.svg" => "../assets/icons/help-about.svg",
    "icons/image-x-generic.svg" => "../assets/icons/image-x-generic.svg",
    "icons/network-wireless.svg" => "../assets/icons/network-wireless.svg",
    "icons/object-select.svg" => "../assets/icons/object-select.svg",
    "icons/package-x-generic.svg" => "../assets/icons/package-x-generic.svg",
    "icons/phone.svg" => "../assets/icons/phone.svg",
    "icons/media-playback-pause.svg" => "../assets/icons/media-playback-pause.svg",
    "icons/process-stop.svg" => "../assets/icons/process-stop.svg",
    "icons/send-to.svg" => "../assets/icons/send-to.svg",
    "icons/sidebar-show.svg" => "../assets/icons/sidebar-show.svg",
    "icons/system-file-manager.svg" => "../assets/icons/system-file-manager.svg",
    "icons/system-software-install.svg" => "../assets/icons/system-software-install.svg",
    "icons/text-x-generic.svg" => "../assets/icons/text-x-generic.svg",
    "icons/user-home.svg" => "../assets/icons/user-home.svg",
    "icons/user-trash.svg" => "../assets/icons/user-trash.svg",
    "icons/utilities-terminal.svg" => "../assets/icons/utilities-terminal.svg",
    "icons/video-x-generic.svg" => "../assets/icons/video-x-generic.svg",
    "icons/view-continuous.svg" => "../assets/icons/view-continuous.svg",
    "icons/view-grid.svg" => "../assets/icons/view-grid.svg",
    "icons/view-list.svg" => "../assets/icons/view-list.svg",
    "icons/view-more.svg" => "../assets/icons/view-more.svg",
    "icons/view-refresh.svg" => "../assets/icons/view-refresh.svg",
    "icons/x-office-document.svg" => "../assets/icons/x-office-document.svg",

    // ── full-colour file-type artwork ──────────────────────────────────────
    "art/apk.svg" => "../assets/art/apk.svg",
    "art/camera.svg" => "../assets/art/camera.svg",
    "art/documents.svg" => "../assets/art/documents.svg",
    "art/magisk.svg" => "../assets/art/magisk.svg",
    "art/movie.svg" => "../assets/art/movie.svg",
    "art/podcasts.svg" => "../assets/art/podcasts.svg",
    "art/screenshots.svg" => "../assets/art/screenshots.svg",
    "art/tar.svg" => "../assets/art/tar.svg",
    "art/telegram.svg" => "../assets/art/telegram.svg",
    "art/txt.svg" => "../assets/art/txt.svg",
    "art/wallpaper.svg" => "../assets/art/wallpaper.svg",
    "art/zip.svg" => "../assets/art/zip.svg",
}

/// Serves [`ASSETS`] to GPUI. Installed on the [`gpui::Application`] in `main`.
pub struct AdbShareAssets;

impl AssetSource for AdbShareAssets {
    fn load(&self, path: &str) -> Result<Option<Cow<'static, [u8]>>> {
        Ok(ASSETS
            .iter()
            .find(|(name, _)| *name == path)
            .map(|(_, bytes)| Cow::Borrowed(*bytes)))
    }

    fn list(&self, _path: &str) -> Result<Vec<SharedString>> {
        Ok(ASSETS
            .iter()
            .map(|(name, _)| SharedString::from(*name))
            .collect())
    }
}

// ── Chrome icons ─────────────────────────────────────────────────────────────

/// The icon names available to [`icon`], without the `icons/` prefix.
///
/// Kept as an enum-free list so a typo in a call site is a `&'static str` that
/// simply renders nothing; `crate::ui::icon_button` is the intended entry point
/// and takes one of these.
pub mod names {
    pub const AUDIO_GENERIC: &str = "audio-x-generic";
    pub const CAMERA_PHOTO: &str = "camera-photo";
    pub const CHECKBOX_CHECKED: &str = "checkbox-checked";
    pub const DIALOG_ERROR: &str = "dialog-error";
    pub const DIALOG_INFORMATION: &str = "dialog-information";
    pub const DIALOG_WARNING: &str = "dialog-warning";
    pub const DOCUMENT_EDIT: &str = "document-edit";
    pub const DOCUMENT_OPEN: &str = "document-open";
    pub const DRIVE_HARDDISK: &str = "drive-harddisk";
    pub const EDIT_COPY: &str = "edit-copy";
    pub const EDIT_DELETE: &str = "edit-delete";
    pub const EDIT_FIND: &str = "edit-find";
    pub const EDIT_PASTE: &str = "edit-paste";
    pub const EDIT_UNDO: &str = "edit-undo";
    pub const EMBLEM_SYNC: &str = "emblem-synchronizing";
    pub const FOLDER: &str = "folder";
    pub const FOLDER_DOCUMENTS: &str = "folder-documents";
    pub const FOLDER_DOWNLOAD: &str = "folder-download";
    pub const FOLDER_MUSIC: &str = "folder-music";
    pub const FOLDER_NEW: &str = "folder-new";
    pub const FOLDER_OPEN: &str = "folder-open";
    pub const FOLDER_PICTURES: &str = "folder-pictures";
    pub const FOLDER_SEND: &str = "folder-send";
    pub const FOLDER_UPLOAD: &str = "folder-upload";
    pub const FOLDER_VIDEOS: &str = "folder-videos";
    pub const GO_NEXT: &str = "go-next";
    pub const GO_PREVIOUS: &str = "go-previous";
    pub const GO_UP: &str = "go-up";
    pub const HELP_ABOUT: &str = "help-about";
    pub const IMAGE_GENERIC: &str = "image-x-generic";
    pub const WIRELESS: &str = "network-wireless";
    pub const PAUSE: &str = "media-playback-pause";
    pub const PLAY: &str = "media-playback-start";
    pub const STOP: &str = "process-stop";
    pub const OBJECT_SELECT: &str = "object-select";
    pub const PACKAGE: &str = "package-x-generic";
    pub const PHONE: &str = "phone";
    pub const SEND_TO: &str = "send-to";
    pub const SIDEBAR_SHOW: &str = "sidebar-show";
    pub const FILE_MANAGER: &str = "system-file-manager";
    pub const SOFTWARE_INSTALL: &str = "system-software-install";
    pub const TEXT_GENERIC: &str = "text-x-generic";
    pub const HOME: &str = "user-home";
    pub const TRASH: &str = "user-trash";
    pub const TERMINAL: &str = "utilities-terminal";
    pub const VIDEO_GENERIC: &str = "video-x-generic";
    pub const VIEW_GRID: &str = "view-grid";
    pub const VIEW_LIST: &str = "view-list";
    pub const VIEW_MORE: &str = "view-more";
    pub const REFRESH: &str = "view-refresh";
    pub const DOCUMENT: &str = "x-office-document";
}

/// Render a monochrome chrome icon tinted to `color`.
///
/// `size` is the square edge in logical pixels; the SVG rasterises at 2x for
/// crispness on HiDPI displays.
pub fn icon(name: &str, size: f32, color: Rgba) -> Svg {
    svg()
        .path(format!("icons/{name}.svg"))
        .size(px(size))
        .text_color(color)
}

/// Full-colour file-type artwork, sized to fit a square box.
pub fn artwork(name: &str, size: f32) -> Img {
    gpui::img(ImageSource::from(SharedString::from(format!(
        "art/{name}.svg"
    ))))
    .size(px(size))
    .object_fit(gpui::ObjectFit::Contain)
}
